type ParagraphText = string;
type ParagraphList = ReadonlyArray<ParagraphText>;

export const paragraphs: ParagraphList = [
  "Thunder is the sound from lightning. Air heats rapidly to extreme temperatures, expands, and creates a shockwave that becomes audible. The rumble often follows the flash since sound travels slower than light. Count five seconds per mile to estimate distance. Seek shelter indoors. Tall structures and open fields increase risk.",
  "Egyptians worshiped cats because they protected grain from rats and snakes, saving food and trade, and because their calm watchful nature matched ideas of order and care. Linked with Bastet, goddess of home, joy, and fertility, cats stood for safety, prosperity, and grace, so families honored them in daily life.",
  "Riding a bicycle builds heart and leg strength, improves balance, and offers low impact exercise for daily health while reducing traffic and pollution. Choose a bike that fits, check brakes and tires, wear a helmet and lights, follow road rules, and ride predictably to enjoy safe, efficient travel every day.",
  "Technology shapes daily life by improving health care, transport, learning, and communication. Smartphones connect families, sensors monitor crops, and clean energy reduces emissions. Cloud tools help small teams build global services. With strong privacy rules and fair access, technology can raise productivity, protect nature, and create new jobs and opportunities.",
  "Swimming is easy on your body and good for your mind. It makes you stronger and fitter. It can be used for anything from relaxed laps to tough intervals, and is suitable for all ages. It is also an important safety skill. If you have a pool or a body of water where you can swim, a cap, and patience, you can get fit, relieve stress, and have fun.",
  "Airplane windows are rounded primarily for safety reasons related to cabin pressure during flight. The rounded shape distributes pressure evenly, preventing stress concentrations at corners that can cause cracks in square windows. This design choice reduces the risk of window failure and enhances the overall structural integrity of the aircraft.",
  "Traveling is a fantastic way to reduce stress and boost happiness, offering a welcome break from routine. It's a fantastic way to boost your creativity, refine your communication skills and broaden your horizons by exposing you to new cultures. You will become incredibly adaptable, your confidence will skyrocket, and you will gain a deeper understanding of yourself and the world.",
  "Stars are truly amazing! They emit light and heat due to nuclear fusion in their cores, where hydrogen atoms fuse into helium, releasing energy. This incredible process generates the light and warmth that we observe as starlight. The light travels across vast distances, some of which we can observe on Earth, allowing us to see stars as distant points of light in the night sky.",
  "Public speaking is such an exciting way to express yourself and connect with an audience. Whether it's in a formal or informal setting, it's a fantastic opportunity to engage and connect with others. Effective public speaking skills are all about clear communication, engaging delivery, and audience awareness.",
  "Skiing is such an amazing sport that combines speed, freedom, and the incredible thrill of gliding downhill. The fresh mountain air and snowy landscapes offer an amazing sense of peace and presence, while the physical activity strengthens muscles and boosts mood. It's an absolutely thrilling sport that connects you with nature and provides the perfect break from everyday stress.",
];
